kind: Service
apiVersion: v1
metadata:
  name: sysdig-agent
  labels:
    app: sysdig-agent
spec:
  type: LoadBalancer
  selector:
    app: sysdig-agent
  ports:
  - protocol: TCP
    port: 7765
    targetPort: 7765
